### ISSUE TITLE
Double escaping of \n in strings

### ISSUE THREAD

**Issue by MrAlek** [KingWu/lang_table#2]
First of all, thank you for this great library @KingWu, we're using it at @doneservices .

An issue we've notices is that if you have strings containing `\n` in AirTable, the outputted JSON after running `lang_table` becomes `\\n` and thus the newline disappears when later converted to Flutter using `gen_lang`.

**Comment by friebetill** [comment]
I find the behaviour odd too. How can one make linebreaks now @KingWu?

**Comment by nekocode** [comment]
You can change the field type to 'Long text' and replace your '\n' with a real line break.
Then this library will generate the right '\n' in output json file.

![image](https://user-images.githubusercontent.com/4783781/86425575-21135000-bd18-11ea-8859-031db7f150a0.png)

**Comment by MrAlek** [comment]
Thanks for the clarification @nekocode
